import {
  blendPartialEntry,
  fdaApprovedOil,
  researchPartial,
} from "@/lib/peptide/lexiconV2/contentEngine/pipeline/packBuilder";
import type { SubstanceCatalogEntry } from "@/lib/peptide/lexiconV2/contentEngine/pipeline/packBuilder";

export const PIPELINE_OIL_ENTRIES: SubstanceCatalogEntry[] = [
  fdaApprovedOil(
    "testosterone-cypionate",
    "Testosteron-Cypionat",
    "Testosterone cypionate",
    "Testosteron-Ersatztherapie bei Hypogonadismus (DEPO-TESTOSTERONE, USA)",
    "In Fachinformationen werden u. a. Polycythämie, kardiovaskuläre Risiken, Prostatabeeinflussung und virilisierende Effekte beschrieben.",
  ),
  fdaApprovedOil(
    "testosterone-enanthate",
    "Testosteron-Enantat",
    "Testosterone enanthate",
    "Testosteron-Ersatztherapie bei Hypogonadismus",
    "In Fachinformationen werden u. a. Polycythämie, kardiovaskuläre Risiken, Prostatabeeinflussung und virilisierende Effekte beschrieben.",
  ),
  fdaApprovedOil(
    "testosterone-propionate",
    "Testosteron-Propionat",
    "Testosterone propionate",
    "Testosteron-Ersatztherapie bei Hypogonadismus",
    "In Fachinformationen werden u. a. Polycythämie, kardiovaskuläre Risiken, Prostatabeeinflussung und virilisierende Effekte beschrieben.",
  ),
  fdaApprovedOil(
    "testosterone-undecanoate",
    "Testosteron-Undecanoat",
    "Testosterone undecanoate",
    "Testosteron-Ersatztherapie bei Hypogonadismus (Aveed, USA)",
    "In Fachinformationen werden u. a. Polycythämie, kardiovaskuläre Risiken und Reaktionen an der Injektionsstelle beschrieben.",
  ),
  fdaApprovedOil(
    "testosterone-suspension",
    "Testosteron-Suspension",
    "Testosterone suspension",
    "Testosteron-Ersatztherapie bei Hypogonadismus",
    "In Fachinformationen werden u. a. Polycythämie, kardiovaskuläre Risiken und Injektionsstellen-Reaktionen beschrieben.",
  ),
  fdaApprovedOil(
    "nandrolone-decanoate",
    "Nandrolon-Decanoat",
    "Nandrolone decanoate",
    "Anämie bei chronischer Niereninsuffizienz und Osteoporose bei postmenopausalen Frauen (Deca-Durabolin, je nach Region)",
    "Anabolisches Steroid – in Fachinformationen u. a. virilisierende Effekte, Leberwerte, kardiovaskuläre Risiken und endokrine Suppression beschrieben.",
  ),
  fdaApprovedOil(
    "estradiol-cypionate",
    "Estradiol-Cypionat",
    "Estradiol cypionate",
    "Östrogenmangel und Hormonersatztherapie (je nach Produkt)",
    "In Fachinformationen werden u. a. thromboembolische Ereignisse, Endometriumhyperplasie und Mammakarzinom-Risiko beschrieben.",
  ),
  fdaApprovedOil(
    "stanozolol-oil",
    "Stanozolol (Öl)",
    "Stanozolol",
    "Hereditäres Angioödem (Winstrol Depot, je nach Region)",
    "Anabolisches Steroid – Lebertoxizität, lipidverändernde Effekte und virilisierende Nebenwirkungen in Fachinformationen beschrieben.",
  ),
  researchPartial(
    "nandrolone-phenylpropionate",
    "Nandrolon-Phenylpropionat (NPP)",
    "injizierbare Öl-/Esterlösung",
    "Nandrolon-Phenylpropionat ist ein kurzer Nandrolon-Ester mit kürzerer Halbwertszeit als Nandrolon-Decanoat.",
    "Nandrolon-Ester werden medizinisch in einigen Indikationen verwendet; NPP ist weniger verbreitet als Decanoat. Missbräuchliche Anwendung birgt erhebliche Risiken.",
    "Medizinische Nutzenprofile gelten für etablierte Nandrolon-Indikationen – nicht für missbräuchliche Zwecke.",
    "Anabolische Steroide bergen Risiken für Leber, Lipidprofil, kardiovaskuläres System und endogenes Hormonsystem.",
    "Als intramuskuläre Öl-in-Öl-Injektion im medizinischen Kontext beschrieben. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Humanstudien existieren für Nandrolon als Wirkstoffklasse in medizinischen Indikationen.",
    "Präklinische anabol/androgen-Daten liegen vor.",
    "Wirkstoffklasse mit medizinischer Historie; NPP-spezifische Zulassung variiert regional.",
  ),
  researchPartial(
    "drostanolone-propionate",
    "Drostanolon-Propionat (Masteron P)",
    "injizierbare Öl-/Esterlösung",
    "Drostanolon-Propionat ist ein DHT-Derivat und anaboles Androgen.",
    "Drostanolon wurde historisch in der Medizin bei Mammakarzinom untersucht. Aktuell kein breit zugelassenes Humanarzneimittel in vielen Märkten.",
    "Historische medizinische Anwendungen sind dokumentiert. Für aktuelle Humantherapie liegen keine etablierten Zulassungsdaten vor.",
    "Anabolische Steroide bergen Risiken für Leber, Lipidprofil und kardiovaskuläres System.",
    "Historisch als intramuskuläre Injektion untersucht. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Historische Humanstudien bei Mammakarzinom; keine moderne breite Zulassung.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Historische medizinische Anwendung; aktuell nicht breit zugelassen.",
  ),
  researchPartial(
    "drostanolone-enanthate",
    "Drostanolon-Enanthat (Masteron E)",
    "injizierbare Öl-/Esterlösung",
    "Drostanolon-Enanthat ist ein länger wirkender Drostanolon-Ester.",
    "Drostanolon wurde historisch in der Medizin bei Mammakarzinom untersucht. Keine breite aktuelle Zulassung in vielen Märkten.",
    "Historische medizinische Anwendungen sind dokumentiert. Für aktuelle Humantherapie liegen keine etablierten Zulassungsdaten vor.",
    "Anabolische Steroide bergen Risiken für Leber, Lipidprofil und kardiovaskuläres System.",
    "Historisch als intramuskuläre Injektion untersucht. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Historische Humanstudien bei Mammakarzinom; keine moderne breite Zulassung.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Historische medizinische Anwendung; aktuell nicht breit zugelassen.",
  ),
  researchPartial(
    "boldenone-undecylenate",
    "Boldenon-Undecylenat (Equipoise)",
    "injizierbare Öl-/Esterlösung",
    "Boldenon-Undecylenat ist ein anaboles Androgen, primär in veterinärmedizinischen Kontexten verwendet.",
    "Boldenon ist in der Humanmedizin nicht zugelassen. Veterinäre Anwendungen (Pferde) sind dokumentiert.",
    "Es liegen keine belastbaren Humanstudien für therapeutische Indikationen vor.",
    "Anabolische Steroide bergen Risiken für Leber, Lipidprofil und kardiovaskuläres System.",
    "Veterinärmedizinisch als intramuskuläre Injektion beschrieben. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Keine Human-Zulassung; veterinäre Daten vorhanden.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Nicht für Human-Gebrauch zugelassen.",
  ),
  researchPartial(
    "boldenone-cypionate",
    "Boldenon-Cypionat",
    "injizierbare Öl-/Esterlösung",
    "Boldenon-Cypionat ist ein Boldenon-Ester – primär im Shop-Katalog, nicht als zugelassenes Humanarzneimittel.",
    "Boldenon ist in der Humanmedizin nicht zugelassen.",
    "Es liegen keine belastbaren Humanstudien vor.",
    "Anabolische Steroide bergen erhebliche Gesundheitsrisiken.",
    "Im Shop als injizierbare Öl-Lösung geführt – keine Injektionsanleitung.",
    "Keine Human-Zulassung.",
    "Präklinische Daten begrenzt.",
    "Nicht zugelassen.",
  ),
  researchPartial(
    "trenbolone-acetate",
    "Trenbolon-Acetat",
    "injizierbare Öl-/Esterlösung",
    "Trenbolon-Acetat ist ein potentes anabolisches Androgen, primär in der Veterinärmedizin (Rinder) verwendet.",
    "Trenbolon ist in der Humanmedizin nicht zugelassen. Veterinäre Implantate sind dokumentiert.",
    "Es liegen keine belastbaren Humanstudien für therapeutische Indikationen vor.",
    "Anabolische Steroide bergen erhebliche Risiken für Leber, Lipidprofil, kardiovaskuläres System und psychische Effekte.",
    "Veterinärmedizinisch verwendet. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Keine Human-Zulassung.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Nicht für Human-Gebrauch zugelassen.",
  ),
  researchPartial(
    "trenbolone-enanthate",
    "Trenbolon-Enanthat",
    "injizierbare Öl-/Esterlösung",
    "Trenbolon-Enanthat ist ein länger wirkender Trenbolon-Ester – nicht als Humanarzneimittel zugelassen.",
    "Trenbolon ist in der Humanmedizin nicht zugelassen.",
    "Es liegen keine belastbaren Humanstudien vor.",
    "Anabolische Steroide bergen erhebliche Gesundheitsrisiken.",
    "Im Shop als injizierbare Öl-Lösung geführt – keine Injektionsanleitung.",
    "Keine Human-Zulassung.",
    "Präklinische Daten begrenzt.",
    "Nicht zugelassen.",
  ),
  researchPartial(
    "trenbolone-hexahydrobenzylcarbonate",
    "Trenbolon-Hexahydrobenzylcarbonat (Parabolan)",
    "injizierbare Öl-/Esterlösung",
    "Trenbolon-Hexahydrobenzylcarbonat ist ein länger wirkender Trenbolon-Ester, historisch als Parabolan vermarktet.",
    "Trenbolon ist in der Humanmedizin nicht zugelassen. Historische Humanpräparate existierten kurzzeitig.",
    "Es liegen keine belastbaren modernen Humanstudien vor.",
    "Anabolische Steroide bergen erhebliche Gesundheitsrisiken.",
    "Historisch als intramuskuläre Injektion. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Keine aktuelle Human-Zulassung.",
    "Präklinische Daten begrenzt.",
    "Nicht zugelassen.",
  ),
  researchPartial(
    "tren-base",
    "Tren BASE",
    "injizierbare Öl-/Esterlösung",
    "Tren BASE bezeichnet Trenbolon ohne Ester – eine Shop-Katalog-Darreichungsform.",
    "Trenbolon ist in der Humanmedizin nicht zugelassen.",
    "Es liegen keine belastbaren Humanstudien vor.",
    "Anabolische Steroide bergen erhebliche Gesundheitsrisiken.",
    "Im Shop als injizierbare Lösung geführt – keine Injektionsanleitung.",
    "Keine Human-Zulassung.",
    "Präklinische Daten begrenzt.",
    "Nicht zugelassen.",
  ),
  researchPartial(
    "methenolone-enanthate",
    "Methenolon-Enanthat (Primobolan Depot)",
    "injizierbare Öl-/Esterlösung",
    "Methenolon-Enanthat ist ein anabolisches Androgen mit relativ mildem Androgenitätsprofil.",
    "Methenolon wurde medizinisch in einigen Regionen verwendet. Aktuelle Zulassung ist begrenzt.",
    "Historische medizinische Anwendungen sind dokumentiert. Für missbräuchliche Zwecke liegen keine sicheren Humanstudien vor.",
    "Anabolische Steroide bergen Risiken für Leber, Lipidprofil und endogenes Hormonsystem.",
    "Historisch als intramuskuläre Injektion. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Historische Humananwendung; begrenzte aktuelle Zulassung.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Begrenzte medizinische Historie; nicht breit zugelassen.",
  ),
  researchPartial(
    "methenolone-acetate",
    "Methenolon-Acetat (Primobolan)",
    "injizierbare Öl-/Esterlösung",
    "Methenolon-Acetat ist der kürzer wirkende Methenolon-Ester.",
    "Methenolon wurde medizinisch in einigen Regionen verwendet. Aktuelle Zulassung ist begrenzt.",
    "Historische medizinische Anwendungen sind dokumentiert.",
    "Anabolische Steroide bergen Risiken für Leber, Lipidprofil und endogenes Hormonsystem.",
    "Historisch als intramuskuläre Injektion. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Historische Humananwendung; begrenzte aktuelle Zulassung.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Begrenzte medizinische Historie; nicht breit zugelassen.",
  ),
  researchPartial(
    "dhb-1-test-cyp",
    "DHB (1-Test Cyp)",
    "injizierbare Öl-/Esterlösung",
    "DHB (Dihydroboldenon, 1-Testosteron-Cypionat) ist ein anabolisches Androgen ohne etablierte Human-Zulassung.",
    "DHB wird im Bodybuilding-Kontext diskutiert. Es gibt keine zugelassene Humantherapie.",
    "Es liegen keine belastbaren Humanstudien vor.",
    "Anabolische Steroide bergen erhebliche Gesundheitsrisiken.",
    "Im Shop als injizierbare Öl-Lösung geführt – keine Injektionsanleitung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische Daten begrenzt.",
    "Nicht zugelassen.",
  ),
  researchPartial(
    "test-base",
    "Testosteron BASE (ohne Ester)",
    "injizierbare Öl-/Esterlösung",
    "Testosteron BASE bezeichnet Testosteron ohne Ester – eine Shop-Katalog-Darreichungsform.",
    "Testosteron als Wirkstoff ist medizinisch etabliert; diese spezifische BASE-Form ist keine standardisierte Zulassungsform.",
    "Medizinische Nutzen/Risiken gelten für Testosteron als Wirkstoffklasse – nicht automatisch für diese Katalogform.",
    "Testosteron bergt Risiken für Polycythämie, kardiovaskuläres System und Prostata.",
    "Im Shop als injizierbare Lösung geführt – keine Injektionsanleitung.",
    "Humanstudien existieren für Testosteron als Wirkstoffklasse.",
    "Präklinische Daten liegen vor.",
    "Wirkstoffklasse etabliert; diese Katalogform nicht standardisiert zugelassen.",
  ),
  researchPartial(
    "ment",
    "MENT (Trestolon-Acetat)",
    "injizierbare Öl-/Esterlösung",
    "MENT (7α-Methyl-19-nortestosteron, Trestolon) ist ein synthetisches anabolisches Androgen in der Forschung.",
    "MENT wurde in klinischen Studien als potenzieller Kontrazeptivum-/Androgen-Kandidat untersucht. Keine breite Zulassung.",
    "In frühen Humanstudien wurden androgen/anabole Effekte beschrieben – begrenzte Daten.",
    "Anabolische Steroide bergen Risiken für endokrine Suppression und kardiovaskuläres System.",
    "In klinischen Studien als intramuskuläre Injektion untersucht. Im Shop nur Katalogform – keine Injektionsanleitung.",
    "Frühe Humanstudien; keine breite Zulassung.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Investigational; keine etablierte Zulassung.",
  ),
  researchPartial(
    "dht-stanolone",
    "DHT (Stanolon)",
    "injizierbare Öl-/Esterlösung",
    "Dihydrotestosteron (DHT, Stanolon) ist ein potentes endogenes Androgen.",
    "DHT ist physiologisch relevant; exogene DHT-Präparate sind nicht als Standard-Humanarzneimittel etabliert.",
    "Endogenes DHT ist gut charakterisiert; exogene Anwendung außerhalb medizinischer Indikationen ist nicht etabliert.",
    "Androgene bergen Risiken für Prostata, kardiovaskuläres System und virilisierende Effekte.",
    "Im Shop als injizierbare Lösung geführt – keine Injektionsanleitung.",
    "Endogenes DHT gut charakterisiert; exogene Therapie nicht standardisiert.",
    "Präklinische androgen-Daten liegen vor.",
    "Endogenes Hormon etabliert; exogene Katalogform nicht standardisiert.",
  ),
  researchPartial(
    "stanozolol-water",
    "Stanozolol (Wasser)",
    "injizierbare Lösung",
    "Stanozolol in wässriger Suspension ist eine alternative Darreichungsform des anabolen Androgens Stanozolol.",
    "Stanozolol ist für Hereditäres Angioödem zugelassen (Winstrol). Diese Katalogform beschreibt nur die Shop-Variante.",
    "Medizinische Nutzen/Risiken gelten für Stanozolol als Wirkstoff – nicht automatisch für diese Katalogform.",
    "Anabolische Steroide bergen Leber-, lipid- und kardiovaskuläre Risiken.",
    "Im Shop als injizierbare wässrige Lösung geführt – keine Injektionsanleitung.",
    "Humanstudien existieren für Stanozolol als Wirkstoff.",
    "Präklinische Daten liegen vor.",
    "Wirkstoff mit medizinischer Zulassung; Katalogform nicht separat standardisiert.",
  ),
  researchPartial(
    "testosterone-600",
    "Testo 600 mg",
    "injizierbare Öl-/Esterlösung",
    "Testo 600 mg ist eine Shop-Katalog-Bezeichnung für eine Testosteron-Öl-Lösung.",
    "Testosteron als Wirkstoff ist medizinisch etabliert; diese spezifische Konzentration/Form ist keine standardisierte Zulassungsform.",
    "Medizinische Nutzen/Risiken gelten für Testosteron als Wirkstoffklasse.",
    "Testosteron bergt Risiken für Polycythämie, kardiovaskuläres System und Prostata.",
    "Im Shop als injizierbare Öl-Lösung geführt – keine Injektionsanleitung.",
    "Humanstudien existieren für Testosteron als Wirkstoffklasse.",
    "Präklinische Daten liegen vor.",
    "Wirkstoffklasse etabliert; Katalogform nicht standardisiert.",
  ),
];

export const PIPELINE_BLEND_ENTRIES: SubstanceCatalogEntry[] = [
  blendPartialEntry(
    "sustanon",
    "Sustanon",
    ["testosterone-propionate", "testosterone-phenylpropionate", "testosterone-isocaproate", "testosterone-decanoate"],
    "Testosteron-Propionat, -Phenylpropionat, -Isocaproate und -Decanoat",
  ),
  blendPartialEntry(
    "supertest",
    "Supertest",
    ["testosterone-propionate", "testosterone-enanthate", "testosterone-cypionate"],
    "Testosteron-Propionat, -Enantat und -Cypionat",
  ),
];
