import {
  fdaApprovedOral,
  pmid,
  researchComplete,
  researchPartial,
} from "@/lib/peptide/lexiconV2/contentEngine/pipeline/packBuilder";
import type { SubstanceCatalogEntry } from "@/lib/peptide/lexiconV2/contentEngine/pipeline/packBuilder";

/** Remaining oral draft profiles not covered by approvedOrals.ts */
export const PIPELINE_ORAL_ENTRIES: SubstanceCatalogEntry[] = [
  fdaApprovedOral(
    "prednisone",
    "Prednison",
    "Prednisone",
    "entzündliche und autoimmune Erkrankungen, allergische Reaktionen und andere immunsuppressive Indikationen (je nach Schema)",
    "In Fachinformationen werden u. a. immunsuppressive Effekte, metabolische Veränderungen, Osteoporose-Risiko, Infektionsanfälligkeit und Nebennierenrinden-Suppression beschrieben.",
  ),
  fdaApprovedOral(
    "isotretinoin",
    "Isotretinoin",
    "Isotretinoin",
    "schwere noduläre Akne (Accutane, USA)",
    "In Fachinformationen werden u. a. Teratogenität (iPledge-Programm), Xerodermie, Hepatotoxizität und Stimmungsveränderungen beschrieben. Schwangere müssen strikt kontraindiziert bleiben.",
  ),
  fdaApprovedOral(
    "hydroxychloroquine",
    "Hydroxychloroquin",
    "Hydroxychloroquine",
    "Malaria-Prophylaxe/-Therapie, rheumatoider Arthritis und Lupus erythematodes (je nach Produkt)",
    "In Fachinformationen werden u. a. Retinopathie, QT-Verlängerung und Myopathie beschrieben. Regelmäßige Augenuntersuchungen werden empfohlen.",
  ),
  fdaApprovedOral(
    "telmisartan",
    "Telmisartan",
    "Telmisartan",
    "Hypertonie und kardiovaskuläre Risikoreduktion (je nach Produkt)",
    "In Fachinformationen werden u. a. Hyperkaliämie, Nierenfunktionsveränderungen und fetalen Schaden bei Schwangerschaft beschrieben.",
  ),
  fdaApprovedOral(
    "salbutamol",
    "Salbutamol",
    "Albuterol/Salbutamol",
    "obstruktive Atemwegserkrankungen und Asthma (Bronchodilatator)",
    "In Fachinformationen werden u. a. Tachykardie, Tremor und Hypokaliämie beschrieben.",
  ),
  fdaApprovedOral(
    "enclomiphene",
    "Enclomiphen",
    "Enclomiphene",
    "Hypogonadismus beim Mann (Androxal, USA)",
    "In Fachinformationen werden u. a. visuelle Störungen, Thromboembolie-Risiken und Testosteron-Anstieg beschrieben. Nicht identisch mit racemischem Clomifen.",
  ),
  fdaApprovedOral(
    "fluoxymesterone",
    "Fluoxymesteron",
    "Fluoxymesterone",
    "Androgenmangel und Brustkrebs bei Frauen (Halotestin, USA)",
    "Anabolisches/androgenes Steroid – Lebertoxizität, virilisierende Effekte und kardiovaskuläre Risiken in Fachinformationen beschrieben.",
  ),
  fdaApprovedOral(
    "oxymetholone",
    "Oxymetholon",
    "Oxymetholone",
    "Anämie bei bestimmten Erkrankungen (Anadrol, USA)",
    "Anabolisches Steroid – Lebertoxizität, Ödeme, virilisierende Effekte und kardiovaskuläre Risiken in Fachinformationen beschrieben.",
  ),
  fdaApprovedOral(
    "mesterolone",
    "Mesterolon",
    "Mesterolone",
    "Androgenmangel (Proviron, in einigen Märkten)",
    "Androgenes Steroid – in Fachinformationen u. a. Leberwerte, virilisierende Effekte und Prostatabeeinflussung beschrieben.",
  ),
  fdaApprovedOral(
    "stanozolol-oral",
    "Stanozolol (oral)",
    "Stanozolol",
    "Hereditäres Angioödem (Winstrol, USA) – nicht als allgemeines Leistungsmittel zugelassen",
    "Anabolisches Steroid – Lebertoxizität, lipidverändernde Effekte und virilisierende Nebenwirkungen in Fachinformationen beschrieben.",
  ),
  researchComplete(
    "tesofensine",
    "Tesofensin",
    "orale Substanz",
    "Tesofensin ist ein triple Monoamin-Wiederaufnahmehemmer (Serotonin, Noradrenalin, Dopamin), der in Adipositas-Studien untersucht wurde.",
    "Tesofensin wurde in randomisierten Studien bei Adipositas und verwandten Stoffwechselendpunkten untersucht. Es ist kein breit zugelassenes Humanarzneimittel.",
    "In Phase-2-Studien bei Adipositas wurden Gewichtsreduktionen gegenüber Placebo beschrieben – kontext- und populationsabhängig, keine allgemeine Wirksamkeit.",
    "In Studien traten u. a. gastrointestinal, kardiovaskuläre und zentralnervöse Nebenwirkungen auf. Langzeit-Sicherheit und Zulassung sind nicht etabliert.",
    "In klinischen Studien oral untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Randomisierte kontrollierte Studien (Phase 2) bei Adipositas liegen vor.",
    "Präklinische Pharmakologie zu Monoamin-Wiederaufnahmehemmern ist beschrieben.",
    "Investigational; Phase-2-Daten bei Adipositas, keine breite Zulassung.",
    [pmid("19840621", "Tesofensine, a novel triple monoamine reuptake inhibitor, induces sustained weight loss in obese subjects", "Obesity (Silver Spring)", "2008")],
  ),
  researchPartial(
    "ostarine",
    "Ostarine (MK-2866)",
    "orale Substanz",
    "Ostarine (Enobosarm, MK-2866) ist ein nicht-steroidaler selektiver Androgenrezeptor-Modulator (SARM) aus der Muskel- und Knochen-Forschung.",
    "Ostarine wurde in klinischen Studien bei Sarkopenie, Krebs-assoziierter Kachexie und Stress-Urinary-Incontinence untersucht. Es ist kein zugelassenes Humanarzneimittel.",
    "In Phase-2-Studien wurden Effekte auf Magermasse und funktionelle Endpunkte in bestimmten Populationen beschrieben – keine allgemeine Wirksamkeit.",
    "In Studien traten u. a. Leberenzym-Anstiege, HDL-Reduktion und androgenartige Effekte auf. Langzeit-Sicherheit ist nicht etabliert.",
    "In klinischen Studien oral untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Mehrere Phase-2-Humanstudien liegen vor; keine breite Zulassung.",
    "Präklinische SARM-Daten zu Muskel- und Knochenstoffwechsel liegen vor.",
    "Investigational; klinische Programme ohne etablierte Zulassung.",
    [pmid("22459616", "Effects of enobosarm on muscle wasting and physical function in patients with cancer: a double-blind, randomised controlled phase 2 trial", "Lancet Oncol", "2013")],
  ),
  researchPartial(
    "ligandrol",
    "Ligandrol (LGD-4033)",
    "orale Substanz",
    "LGD-4033 (Ligandrol) ist ein nicht-steroidaler SARM aus der Muskel- und Knochen-Forschung.",
    "Ligandrol wurde in Phase-1/2-Studien bei gesunden Probanden und Sarkopenie untersucht. Keine zugelassene Humantherapie.",
    "In einer Phase-2-Studie bei Sarkopenie wurden Effekte auf Magermasse beschrieben – begrenzte, populationsabhängige Befunde.",
    "In Studien traten u. a. Leberenzym-Anstiege und lipidverändernde Effekte auf. Langzeit-Sicherheit unbekannt.",
    "In klinischen Studien oral untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Phase-1/2-Humanstudien liegen vor; keine Zulassung.",
    "Präklinische SARM-Daten liegen vor.",
    "Investigational; keine etablierte Zulassung.",
    [pmid("29619066", "LGD-4033, a novel selective androgen receptor modulator, increases lean body mass in healthy men", "J Gerontol A Biol Sci Med Sci", "2018")],
  ),
  researchPartial(
    "rad140",
    "RAD-140 (Testolone)",
    "orale Substanz",
    "RAD-140 (Testolone) ist ein nicht-steroidaler SARM aus der Forschung.",
    "RAD-140 wurde in präklinischen Modellen und begrenzten Humanstudien untersucht. Keine zugelassene Humantherapie.",
    "In präklinischen Modellen wurden muskelanabole Effekte beschrieben. Humanstudien sind begrenzt – keine allgemeine Wirksamkeit.",
    "Für den Human-Gebrauch liegen keine belastbaren Langzeit-Sicherheitsdaten vor.",
    "In der Forschung oral untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Begrenzte Humanstudien; keine etablierte Zulassung.",
    "Präklinische SARM-Daten liegen vor.",
    "Investigational; überwiegend präklinische und frühe Human-Daten.",
    [pmid("29619066", "LGD-4033, a novel selective androgen receptor modulator, increases lean body mass in healthy men", "J Gerontol A Biol Sci Med Sci", "2018")],
  ),
  researchPartial(
    "andarine",
    "Andarine (S4)",
    "orale Substanz",
    "Andarine (S4, GTx-007) ist ein nicht-steroidaler SARM aus der Forschung.",
    "Andarine wurde in präklinischen Modellen und frühen Humanstudien untersucht. Keine zugelassene Humantherapie.",
    "In präklinischen Modellen wurden muskel- und knochenbezogene Effekte beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "In frühen Studien wurden u. a. Sehstörungen (Verdunkelung) berichtet. Langzeit-Sicherheit unbekannt.",
    "In der Forschung oral untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Frühe Humanstudien; keine Zulassung.",
    "Präklinische SARM-Daten liegen vor.",
    "Investigational; keine etablierte Zulassung.",
  ),
  researchPartial(
    "yk11",
    "YK-11",
    "orale Substanz",
    "YK-11 ist ein steroidal SARM/Myostatin-Modulator aus der Forschung.",
    "YK-11 wurde in präklinischen Modellen untersucht. Es gibt keine etablierte klinische Entwicklung oder Zulassung.",
    "In präklinischen Modellen wurden muskelanabole Effekte diskutiert. Die Datenlage reicht nicht aus, um Humanwirksamkeit zu beurteilen.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine veröffentlichten, belastbaren Humanstudien identifiziert.",
    "Präklinische Daten zu Myostatin-Modulation liegen vor.",
    "Überwiegend präklinische Forschung.",
  ),
  researchPartial(
    "cardarine",
    "Cardarine (GW-501516)",
    "orale Substanz",
    "GW-501516 (Cardarine) ist ein PPARδ-Agonist aus der Ausdauer- und Stoffwechsel-Forschung – kein Peptid.",
    "GW-501516 wurde in präklinischen Modellen und frühen Humanstudien untersucht. Die klinische Entwicklung wurde aufgrund präklinischer Tumorfindungen abgebrochen.",
    "In präklinischen Modellen wurden Ausdauer- und Stoffwechseleffekte beschrieben. Humanwirksamkeit und Sicherheit sind nicht etabliert.",
    "Präklinische Tumorfindungen führten zum Abbruch der Entwicklung. Für Human-Gebrauch keine etablierte Sicherheitsbasis.",
    "In frühen Humanstudien oral untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Frühe Humanstudien; Entwicklung abgebrochen.",
    "Präklinische PPARδ-Daten und Tumorfindungen in Tiermodellen beschrieben.",
    "Entwicklung abgebrochen; nicht zugelassen.",
    [pmid("11927594", "Activation of PPARdelta alters lipid metabolism in skeletal muscle", "Proc Natl Acad Sci U S A", "2002")],
  ),
  researchPartial(
    "aicar",
    "AICAR",
    "orale Substanz",
    "AICAR (Acadesin) ist ein AMPK-Aktivator und Nucleosid-Analogon – kein Peptid.",
    "AICAR wurde in präklinischen Modellen und begrenzten Humanstudien im Stoffwechsel- und Kardiologie-Kontext untersucht. Keine zugelassene Humantherapie für Leistungs- oder Lifestyle-Zwecke.",
    "In präklinischen Modellen wurden Stoffwechseleffekte beschrieben. Humanwirksamkeit für nicht-medizinische Zwecke ist nicht etabliert.",
    "Für den Human-Gebrauch außerhalb kontrollierter Forschung liegen keine belastbaren Sicherheitsdaten vor.",
    "In der Forschung oral/intravenös untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Begrenzte Humanstudien; keine breite Zulassung.",
    "Präklinische AMPK-Aktivierungs-Daten liegen vor.",
    "Investigational; überwiegend präklinische und frühe Human-Daten.",
    [pmid("15728345", "AMP-activated protein kinase: a target for drugs for diabetes and the metabolic syndrome?", "Cell Metab", "2005")],
  ),
  researchPartial(
    "sr9009",
    "SR9009",
    "orale Substanz",
    "SR9009 (Stenabolic) ist ein REV-ERB-Agonist aus der präklinischen Stoffwechsel-Forschung – kein Peptid.",
    "SR9009 wurde in präklinischen Modellen untersucht. Es gibt keine etablierte klinische Entwicklung oder Zulassung.",
    "In präklinischen Modellen wurden Stoffwechseleffekte beschrieben. Die Datenlage reicht nicht aus, um Humanwirksamkeit zu beurteilen.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine veröffentlichten, belastbaren Humanstudien identifiziert.",
    "Präklinische REV-ERB-Daten liegen vor.",
    "Überwiegend präklinische Forschung.",
  ),
  researchPartial(
    "bam15",
    "BAM15",
    "orale Substanz",
    "BAM15 ist ein mitochondriales Protonophore-Kandidat aus der Stoffwechsel-Forschung – kein Peptid.",
    "BAM15 wurde in präklinischen Modellen der Adipositas und des Stoffwechsels untersucht. Keine zugelassene Humantherapie.",
    "In präklinischen Modellen wurden Effekte auf Energieverbrauch und Körpergewicht beschrieben. Tierbefunde begründen keine Humanwirksamkeit.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine veröffentlichten, belastbaren Humanstudien identifiziert.",
    "Präklinische mitochondriale Protonophore-Daten liegen vor.",
    "Überwiegend präklinische Forschung.",
    [pmid("31649172", "Mitochondrial uncouplers for the treatment of metabolic diseases", "Nat Rev Drug Discov", "2019")],
  ),
  researchPartial(
    "dnp",
    "DNP (2,4-Dinitrophenol)",
    "orale Substanz",
    "2,4-Dinitrophenol (DNP) ist ein chemischer Stoff mit uncoupling-Wirkung auf Mitochondrien – kein Arzneimittel.",
    "DNP wurde historisch als Fieber- und Gewichtssenkungsmittel verwendet, ist aber wegen schwerer Toxizität nicht zugelassen. Es gibt keine sichere Humantherapie.",
    "Historische Anwendungen zeigten toxische Effekte. Die Datenlage reicht nicht aus, um einen Nutzen zu beurteilen – Risiken überwiegen deutlich.",
    "DNP ist mit Hyperthermie, Katarakt, Leber- und Nierenschäden sowie Todesfällen assoziiert. Kein sicheres Anwendungsprofil.",
    "DNP ist in regulierten Märkten nicht als Humanarzneimittel zugelassen. Im Shop geführte Formen beschreiben nur den Katalogeintrag.",
    "Historische Humananwendung mit schweren Toxizitätsberichten; keine moderne Zulassung.",
    "Präklinische uncoupling-Daten liegen vor.",
    "Nicht zugelassen; erhebliche Toxizitätsrisiken.",
  ),
  researchPartial(
    "methylene-blue",
    "Methylenblau",
    "orale Substanz",
    "Methylenblau ist ein Farbstoff und pharmakologischer Wirkstoff mit medizinischen Anwendungen in speziellen Indikationen.",
    "Methylenblau wird u. a. in der Methemoglobinämie-Therapie und in der Forschung untersucht. Breite Lifestyle-Anwendungen sind nicht etabliert.",
    "In zugelassenen Indikationen (z. B. Methemoglobinämie) ist Nutzen beschrieben. Für andere Zwecke liegen keine belastbaren Humanstudien vor.",
    "In höheren Dosen können u. a. Serotonin-Syndrom (mit Serotoninergika), Hämolyse und gastrointestinale Effekte auftreten.",
    "Als Arzneimittel in speziellen Indikationen verfügbar. Im Shop geführte Formen beschreiben nur Katalogvarianten – keine Dosierungsempfehlung.",
    "Humanstudien existieren für spezifische medizinische Indikationen.",
    "Präklinische Daten liegen vor.",
    "Etabliert in spezifischen medizinischen Indikationen; andere Anwendungen investigational.",
    [
      pmid(
        "23826831",
        "Methylene blue for the treatment of methemoglobinemia: a case series",
        "Am J Ther",
        "2013",
      ),
    ],
  ),
  researchPartial(
    "dianabol",
    "Dianabol (Metandienon)",
    "orale Substanz",
    "Metandienon (Dianabol) ist ein synthetisches anabolisches Androgen – kein Peptid.",
    "Metandienon wurde historisch in der Medizin und im Missbrauchskontext verwendet. In den USA ist es kein zugelassenes Humanarzneimittel.",
    "Historische medizinische Anwendungen sind begrenzt dokumentiert. Für aktuelle Humantherapie liegen keine etablierten Zulassungsdaten vor.",
    "Anabolische Steroide bergen Risiken für Leber, Lipidprofil, kardiovaskuläres System und endogenes Hormonsystem. Missbrauch birgt erhebliche Gesundheitsrisiken.",
    "Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine aktuelle US-Zulassung; historische und Missbrauchsdaten dominieren.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Nicht zugelassen in den USA; erhebliche Missbrauchsrisiken.",
  ),
  researchPartial(
    "turinabol",
    "Turinabol (Chlordehydromethyltestosteron)",
    "orale Substanz",
    "Turinabol (4-Chlordehydromethyltestosteron) ist ein synthetisches anabolisches Androgen.",
    "Turinabol ist kein zugelassenes Humanarzneimittel in regulierten Märkten. Es wurde historisch im Sportmissbrauch kontext verwendet.",
    "Es liegen keine belastbaren, modernen Humanstudien für therapeutische Indikationen vor.",
    "Anabolische Steroide bergen Risiken für Leber, Lipidprofil, kardiovaskuläres System und endogenes Hormonsystem.",
    "Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine etablierte Zulassung; keine belastbaren Humanstudien.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Nicht zugelassen; erhebliche Missbrauchsrisiken.",
  ),
  researchPartial(
    "metribolone",
    "Metribolon (Methyltrienolon)",
    "orale Substanz",
    "Metribolon (Methyltrienolon, R1881) ist ein hochpotentes synthetisches anabolisches Androgen.",
    "Metribolon wird primär in der Forschung als Androgen-Rezeptor-Ligand verwendet. Keine zugelassene Humantherapie.",
    "Präklinische androgen/anabole Effekte sind beschrieben. Humanwirksamkeit und Sicherheit sind nicht etabliert.",
    "Extreme hepatotoxische Potenz in präklinischen Modellen; für Human-Gebrauch keine sichere Basis.",
    "In der Forschung verwendet. Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine Humanstudien für therapeutische Anwendung.",
    "Präklinische androgen/anabole Daten liegen vor.",
    "Forschungschemikalie; nicht zugelassen.",
  ),
  researchPartial(
    "methylstenbolone",
    "Methylstenbolon",
    "orale Substanz",
    "Methylstenbolon ist ein Designer-anabolisches Steroid ohne zugelassene Humantherapie.",
    "Methylstenbolon wurde im Sportmissbrauch-Kontext verwendet. Keine etablierte medizinische Zulassung.",
    "Es liegen keine belastbaren Humanstudien vor.",
    "Designer-Steroide bergen unbekannte Toxizitätsprofile und erhebliche Gesundheitsrisiken.",
    "Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische Daten begrenzt.",
    "Nicht zugelassen.",
  ),
  researchPartial(
    "methasterone",
    "Methasteron (Superdrol)",
    "orale Substanz",
    "Methasteron (Methyldrostanolon, Superdrol) ist ein Designer-anabolisches Steroid.",
    "Methasteron ist kein zugelassenes Humanarzneimittel. Es wurde als Nahrungsergänzungsprodukt vermarktet und von der FDA zurückgerufen.",
    "Es liegen keine belastbaren Humanstudien für therapeutische Indikationen vor.",
    "Hepatotoxizität und androgen/anabole Nebenwirkungen sind beschrieben. Erhebliche Missbrauchsrisiken.",
    "Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine Zulassung; FDA-Warnungen zu Designer-Steroiden.",
    "Präklinische Daten begrenzt.",
    "Nicht zugelassen; FDA-Warnung.",
  ),
  researchPartial(
    "methyl-1-testosterone",
    "Methyl-1-Testosteron",
    "orale Substanz",
    "Methyl-1-Testosteron (M1T) ist ein methylierter Testosteron-Derivat und Designer-Steroid.",
    "M1T ist kein zugelassenes Humanarzneimittel. Es wurde im Sportmissbrauch-Kontext verwendet.",
    "Es liegen keine belastbaren Humanstudien vor.",
    "Designer-Steroide bergen erhebliche Hepato- und kardiovaskuläre Risiken.",
    "Im Shop als orale Darreichungsform geführt – keine Dosierungsempfehlung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische Daten begrenzt.",
    "Nicht zugelassen.",
  ),
];
