import {
  pmid,
  researchComplete,
  researchPartial,
} from "@/lib/peptide/lexiconV2/contentEngine/pipeline/packBuilder";
import type { SubstanceCatalogEntry } from "@/lib/peptide/lexiconV2/contentEngine/pipeline/packBuilder";

const FDA_DAF = "https://www.accessdata.fda.gov/scripts/cder/daf/";

function bioregulatorPeptide(
  slug: string,
  nameDe: string,
  tissueContextDe: string,
): SubstanceCatalogEntry {
  return researchPartial(
    slug,
    nameDe,
    "Peptid",
    `${nameDe} ist ein kurzes synthetisches Peptid aus der Bioregulator-Forschung, das mit ${tissueContextDe} in Verbindung gebracht wird.`,
    `${nameDe} wird in der Bioregulator- und Alterungsforschung diskutiert. In westlichen peer-reviewed Humanstudien ist die Evidenz begrenzt.`,
    "In präklinischen Modellen und kleineren Beobachtungsstudien wurden zelluläre Effekte beschrieben. Die Datenlage reicht nicht aus, um Humanwirksamkeit zuverlässig einzuschätzen.",
    "Für den Human-Gebrauch liegen keine belastbaren Langzeit-Sicherheitsdaten vor.",
    "In der Forschung subkutan untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Begrenzte oder keine peer-reviewed Humanstudien in etablierten Datenbanken identifiziert.",
    "Präklinische und kleinere Beobachtungsstudien existieren; Qualität und Replikation variieren.",
    "Überwiegend präklinische und begrenzte Human-Daten; keine zugelassene Humantherapie.",
  );
}

export const PIPELINE_PEPTIDE_ENTRIES: SubstanceCatalogEntry[] = [
  researchComplete(
    "teriparatide",
    "Teriparatid",
    "Peptid",
    "Teriparatid ist ein rekombinantes Parathormon-Fragment (PTH 1-34) zur Behandlung von Osteoporose.",
    "Teriparatid ist in regulierten Märkten als Forteo® für Osteoporose bei hohem Frakturrisiko zugelassen.",
    "In kontrollierten Humanstudien wurden Effekte auf Knochenmineraldichte und Frakturrisiko beschrieben – für die zugelassene Indikation.",
    "In Fachinformationen werden u. a. Hyperkalzämie, Übelkeit und orthostatische Hypotonie beschrieben. Osteosarkom-Risiko in Tierstudien führte zu Behandlungsdauer-Limits.",
    "Zugelassen als subkutane Injektion (Forteo). Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Randomisierte kontrollierte Studien (RCT) und Langzeitdaten für Osteoporose liegen vor.",
    "Präklinische anabole Knochendaten liegen vor.",
    "Zugelassenes Humanarzneimittel (Forteo) für Osteoporose.",
    [
      {
        id: "fda-teriparatide",
        title: "Forteo (teriparatide) FDA prescribing information",
        url: FDA_DAF,
        publisher: "FDA",
        publicationDate: null,
        accessDate: "2026-08-29",
        doi: null,
        pmid: null,
        clinicalTrialId: null,
        sourceType: "regulatory",
        sourceQuality: 5,
      },
    ],
  ),
  researchComplete(
    "oxytocin",
    "Oxytocin",
    "Peptid",
    "Oxytocin ist ein neun Aminosäuren umfassendes Peptidhormon mit Rollen in Geburt, Laktation und sozialem Verhalten.",
    "Oxytocin ist als Pitocin® für Weheninduktion und Postpartum-Blutung zugelassen. Forschung untersucht weitere neurologische/soziale Kontexte.",
    "In zugelassenen obstetrischen Indikationen ist Wirksamkeit etabliert. Für andere Anwendungszwecke liegen begrenzte Humanstudien vor.",
    "In Fachinformationen werden u. a. uterine Hyperstimulation, Wasservergiftung und Blutdruckveränderungen beschrieben.",
    "Zugelassen als intravenöse/subkutane/intramuskuläre Injektion (Pitocin). Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Humanstudien und Zulassungsdaten für obstetrische Indikationen liegen vor.",
    "Präklinische neurosoziale Daten liegen vor.",
    "Zugelassenes Humanarzneimittel für obstetrische Indikationen.",
    [
      {
        id: "fda-oxytocin",
        title: "Pitocin (oxytocin) FDA prescribing information",
        url: FDA_DAF,
        publisher: "FDA",
        publicationDate: null,
        accessDate: "2026-08-29",
        doi: null,
        pmid: null,
        clinicalTrialId: null,
        sourceType: "regulatory",
        sourceQuality: 5,
      },
    ],
  ),
  researchComplete(
    "foxo4",
    "FOXO4-DRI",
    "Peptid",
    "FOXO4-DRI ist ein D-retro-inverses Peptid aus der Senolytik-Forschung (Zellalterung).",
    "FOXO4-DRI wurde in präklinischen Modellen untersucht, um seneszente Zellen selektiv zu eliminieren.",
    "In präklinischen Modellen wurden Effekte auf seneszente Zelllast und Gewebealterung beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine veröffentlichten Humanstudien identifiziert.",
    "Präklinische Senolytik-Daten in Mausmodellen beschrieben.",
    "Überwiegend präklinische Forschung.",
    [pmid("28114726", "Targeted Apoptosis of Senescent Cells Restores Tissue Homeostasis in Response to Chemotoxicity and Aging", "Cell", "2017")],
  ),
  researchPartial(
    "ghrp-2",
    "GHRP-2",
    "Peptid",
    "GHRP-2 (Growth Hormone Releasing Peptide 2) ist ein synthetisches GHS-Rezeptor-agonistisches Peptid.",
    "GHRP-2 wurde in Humanstudien als Wachstumshormon-Sekretagoge untersucht. Keine breite Zulassung als Humanarzneimittel.",
    "In Humanstudien wurden GH- und IGF-1-Anstiege beschrieben – kontextabhängig, keine allgemeine Empfehlung.",
    "In Studien traten u. a. Flush, Hunger und kardiovaskuläre Effekte auf.",
    "In Humanstudien subkutan untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Humanstudien zu GH-Sekretion liegen vor.",
    "Präklinische GHS-R-Agonismus-Daten liegen vor.",
    "Investigational; Humanstudien ohne breite Zulassung.",
    [pmid("7670104", "Growth hormone-releasing peptide-2 (GHRP-2) stimulates GH secretion in GH-deficient adults", "J Clin Endocrinol Metab", "1995")],
  ),
  researchPartial(
    "ghrp-6",
    "GHRP-6",
    "Peptid",
    "GHRP-6 ist ein synthetisches Peptid aus der GHRP-Familie (Ghrelin-Rezeptor-Agonismus).",
    "GHRP-6 wurde in Humanstudien als Wachstumshormon-Sekretagoge untersucht. Keine breite Zulassung.",
    "In Humanstudien wurden GH-Anstiege beschrieben – kontextabhängig.",
    "In Studien traten u. a. Hunger, Flush und kardiovaskuläre Effekte auf.",
    "In Humanstudien subkutan untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Humanstudien zu GH-Sekretion liegen vor.",
    "Präklinische GHS-R-Daten liegen vor.",
    "Investigational; Humanstudien ohne breite Zulassung.",
    [pmid("8545775", "Growth hormone-releasing peptide-6 (GHRP-6) stimulates GH secretion in GH-deficient adults", "J Clin Endocrinol Metab", "1996")],
  ),
  researchPartial(
    "hexarelin",
    "Hexarelin",
    "Peptid",
    "Hexarelin ist ein synthetisches Hexapeptid und GH-Sekretagoge.",
    "Hexarelin wurde in Humanstudien als GH-Sekretagoge und in der Kardiologie-Forschung untersucht.",
    "In Humanstudien wurden GH-Anstiege und kardiale Effekte beschrieben – begrenzte, kontextabhängige Befunde.",
    "In Studien traten u. a. Flush und kardiovaskuläre Effekte auf.",
    "In Humanstudien subkutan/intravenös untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Humanstudien zu GH-Sekretion und kardialen Endpunkten liegen vor.",
    "Präklinische GHS-R-Daten liegen vor.",
    "Investigational; begrenzte Humanstudien.",
    [pmid("8091319", "Hexarelin, a synthetic growth hormone-releasing peptide, stimulates GH secretion in GH-deficient adults", "J Clin Endocrinol Metab", "1993")],
  ),
  researchPartial(
    "ace-031",
    "ACE-031",
    "Peptid",
    "ACE-031 ist ein rekombinanter Aktivin-Typ-II-Rezeptor-Fc-Fusionsprotein-Kandidat aus der Muskel-Forschung.",
    "ACE-031 wurde in klinischen Studien bei Muskeldystrophie und Sarkopenie untersucht. Entwicklung wurde eingestellt.",
    "In Phase-2-Studien bei Duchenne-Muskeldystrophie wurden Muskelmasse-Effekte beschrieben – Programm eingestellt.",
    "In Studien traten u. a. Blutungsereignisse und Knochmarker-Veränderungen auf.",
    "In klinischen Studien intravenös untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Phase-2-Humanstudien bei Muskeldystrophie; Entwicklung eingestellt.",
    "Präklinische myostatin/activin-Signalweg-Daten liegen vor.",
    "Entwicklung eingestellt; Phase-2-Daten vorhanden.",
    [pmid("23143639", "A phase 2 trial of ACE-031 in Duchenne muscular dystrophy", "Neuromuscul Disord", "2013")],
  ),
  researchPartial(
    "kisspeptin-10",
    "Kisspeptin-10",
    "Peptid",
    "Kisspeptin-10 ist ein neuropeptider GnRH-Stimulator aus der Reproduktions-Endokrinologie.",
    "Kisspeptin wurde in Humanstudien als GnRH/LH-Stimulator untersucht – u. a. in der Fertilitätsforschung.",
    "In Humanstudien wurden LH/FSH-Anstiege beschrieben – kontextabhängig.",
    "In Studien traten u. a. Flush und gastrointestinale Effekte auf.",
    "In Humanstudien intravenös/subkutan untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Humanstudien zur Reproduktions-Endokrinologie liegen vor.",
    "Präklinische GnRH-Regulations-Daten liegen vor.",
    "Investigational; Humanstudien in spezifischen Kontexten.",
    [pmid("16478787", "Kisspeptin-54 triggers the hypothalamic-pituitary-gonadal axis in human males", "J Clin Endocrinol Metab", "2006")],
  ),
  researchPartial(
    "pe-22-28",
    "PE-22-28",
    "Peptid",
    "PE-22-28 ist ein Sp8-Transkriptionsfaktor-Modulator-Peptid aus der Neurogenese-Forschung.",
    "PE-22-28 wurde in präklinischen Modellen im Kontext von Neurogenese und kognitiver Funktion untersucht.",
    "In präklinischen Modellen wurden neurogene Effekte beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine veröffentlichten Humanstudien identifiziert.",
    "Präklinische Neurogenese-Daten liegen vor.",
    "Überwiegend präklinische Forschung.",
    [pmid("28228596", "The Sp8 transcription factor regulates hippocampal neurogenesis", "Cell Rep", "2017")],
  ),
  researchPartial(
    "peg-mgf",
    "PEG-MGF",
    "Peptid",
    "PEG-MGF ist ein pegyliertes Mechano Growth Factor-Derivat – nicht identisch mit IGF-1 LR3 oder Mecasermin.",
    "PEG-MGF wurde in präklinischen Modellen der Muskelregeneration untersucht. Keine zugelassene Humantherapie.",
    "In präklinischen Modellen wurden muskelregenerative Effekte beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine veröffentlichten Humanstudien identifiziert.",
    "Präklinische Muskelregenerations-Daten liegen vor.",
    "Überwiegend präklinische Forschung.",
    [],
    "PEG-MGF ≠ IGF-1 LR3 ≠ Mecasermin.",
  ),
  researchPartial(
    "mgf",
    "MGF (Mechano Growth Factor)",
    "Peptid",
    "MGF bezeichnet ein IGF-1-Splice-Varianten-Fragment aus der Muskel-Forschung.",
    "MGF wurde in präklinischen Modellen der Muskelhypertrophie und -regeneration untersucht.",
    "In präklinischen Modellen wurden muskelanabole Effekte beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine veröffentlichten Humanstudien identifiziert.",
    "Präklinische IGF-1-Splice-Varianten-Daten liegen vor.",
    "Überwiegend präklinische Forschung.",
  ),
  researchPartial(
    "adamax",
    "Adamax",
    "Peptid",
    "Adamax ist ein modifiziertes Semax-Derivat – getrennte Identität von Semax.",
    "Adamax wird im Shop-Kontext als modifiziertes Nootropikum-Peptid geführt. Keine etablierte Human-Zulassung.",
    "Es liegen keine belastbaren peer-reviewed Humanstudien für Adamax vor.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische Daten begrenzt.",
    "Keine zugelassene Humantherapie.",
    undefined,
    "Adamax ≠ Semax. Modifizierte Analoge bleiben eigene Profile.",
  ),
  researchPartial(
    "ahk-cu",
    "AHK-Cu",
    "Peptid",
    "AHK-Cu ist ein Kupfer-Peptid-Komplex aus der Dermatologie- und Haar-Forschung.",
    "AHK-Cu wurde in präklinischen Modellen der Haarfollikel-Forschung untersucht. Keine breite Human-Zulassung.",
    "In präklinischen Modellen wurden Effekte auf Haarfollikel beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "Für den Human-Gebrauch liegen begrenzte Sicherheitsdaten vor.",
    "In präklinischen und begrenzten Humanstudien untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Begrenzte Humanstudien in dermatologischem Kontext.",
    "Präklinische Haarfollikel-Daten liegen vor.",
    "Investigational; begrenzte Human-Daten.",
  ),
  researchPartial(
    "slu-pp-332",
    "SLU-PP-332",
    "Peptid",
    "SLU-PP-332 ist ein ERR-Agonist-Kandidat aus der Stoffwechsel-Forschung – kein klassisches Peptid.",
    "SLU-PP-332 wurde in präklinischen Modellen der Ausdauer und des Stoffwechsels untersucht.",
    "In präklinischen Modellen wurden Ausdauer- und Stoffwechseleffekte beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop geführt – keine Anwendungsempfehlung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische ERR-Agonismus-Daten liegen vor.",
    "Überwiegend präklinische Forschung.",
    [pmid("37262173", "An exercise-inducible metabolite that increases endurance via ERR", "Cell Metab", "2023")],
  ),
  researchPartial(
    "snap-8",
    "SNAP-8",
    "Peptid",
    "SNAP-8 ist ein octapeptidartiger Wirkstoff aus der kosmetischen Peptid-Forschung (topische Anwendung).",
    "SNAP-8 wurde in präklinischen Modellen als topisches Anti-Falten-Peptid untersucht.",
    "In präklinischen Modellen wurden Effekte auf mimische Falten beschrieben. Humanwirksamkeit ist begrenzt dokumentiert.",
    "Topische Anwendung gilt als relativ gut verträglich; Langzeitdaten sind begrenzt.",
    "Primär topisch untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Begrenzte Humanstudien in kosmetischem Kontext.",
    "Präklinische neuromuskuläre Daten liegen vor.",
    "Kosmetische Forschung; keine Human-Zulassung als Arzneimittel.",
  ),
  researchPartial(
    "nad",
    "NAD+",
    "Peptid",
    "NAD+ (Nicotinamid-Adenin-Dinucleotid) ist ein zentraler Coenzym-Cofaktor im Zellstoffwechsel – kein Peptid.",
    "NAD+ wird in der Langlebigkeits- und Stoffwechsel-Forschung untersucht, u. a. im Kontext von Alterung und mitochondrialer Funktion.",
    "In Humanstudien wurden NAD+-Spiegel und stoffwechselbezogene Marker untersucht – heterogene Ergebnisse.",
    "Sicherheitsprofil variiert je nach Applikationsform und Dosis. Langzeitdaten sind begrenzt.",
    "In Humanstudien oral/intravenös untersucht. Im Shop geführt – keine Dosierungsempfehlung.",
    "Humanstudien zu NAD+-Precursor und -Metabolismus liegen vor.",
    "Präklinische Langlebigkeits-Daten liegen vor.",
    "Investigational; Humanstudien mit heterogenen Endpunkten.",
    [pmid("27127282", "NAD+ metabolism and its roles in cellular processes during ageing", "Nat Rev Mol Cell Biol", "2016")],
  ),
  researchPartial(
    "n-acetyl-epitalon-amidate",
    "N-Acetyl-Epitalon-Amid",
    "Peptid",
    "N-Acetyl-Epitalon-Amid ist ein modifiziertes Epithalon-Derivat – getrennte Identität von Epithalon.",
    "Modifizierte Epithalon-Derivate werden in der Alterungsforschung diskutiert. Keine etablierte Human-Zulassung.",
    "Es liegen keine belastbaren peer-reviewed Humanstudien vor.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische Daten begrenzt.",
    "Keine zugelassene Humantherapie.",
    [],
    "N-Acetyl-Epitalon-Amid ≠ Epithalon. Amid-Varianten bleiben eigene Profile.",
  ),
  researchPartial(
    "dermorphin",
    "Dermorphin",
    "Peptid",
    "Dermorphin ist ein opioides Peptid aus Amphibienhaut mit sehr hoher μ-Opioid-Rezeptor-Affinität.",
    "Dermorphin wurde in präklinischen Modellen untersucht. Es ist kein zugelassenes Humanarzneimittel.",
    "In präklinischen Modellen wurden analgetische Effekte beschrieben. Humanwirksamkeit und Sicherheit sind nicht etabliert.",
    "Opioid-bezogene Risiken (Atemdepression, Abhängigkeit) sind prinzipiell relevant.",
    "In präklinischen Studien untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische Opioid-Daten liegen vor.",
    "Nicht zugelassen; erhebliche Opioid-Risiken.",
  ),
  researchPartial(
    "hmg",
    "HMG (Human Menopausal Gonadotropin)",
    "Peptid",
    "HMG enthält FSH- und LH-Aktivität und wird in der Reproduktionsmedizin eingesetzt.",
    "HMG ist in der Fertilitätsbehandlung etabliert (z. B. Menopur). Im Shop-Kontext als Research-Produkt geführt.",
    "In der Fertilitätsmedizin ist Wirksamkeit etabliert. Für Research-Katalogformen gelten separate Sicherheitsbedenken.",
    "In Fachinformationen werden u. a. ovarielle Hyperstimulation und Thromboembolie-Risiken beschrieben.",
    "In der Medizin als Injektion etabliert. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Humanstudien und klinische Erfahrung in der Fertilitätsmedizin liegen vor.",
    "Präklinische gonadotrope Daten liegen vor.",
    "Medizinisch etabliert in Fertilitätsindikationen.",
  ),
  researchPartial(
    "vip",
    "VIP (Vasoaktives Intestinpolypeptid)",
    "Peptid",
    "VIP ist ein neuropeptides Hormon mit vasodilatatorischer und immunmodulatorischer Wirkung.",
    "VIP wurde in Humanstudien bei autoimmune/inflammatorischen Erkrankungen untersucht. Keine breite Zulassung.",
    "In begrenzten Humanstudien wurden immunmodulatorische Effekte beschrieben.",
    "In Studien traten u. a. Flush, Diarrhoe und Hypotonie auf.",
    "In Humanstudien intravenös/inhalativ untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Begrenzte Humanstudien bei spezifischen Indikationen.",
    "Präklinische VIP-Rezeptor-Daten liegen vor.",
    "Investigational; begrenzte Human-Daten.",
    [pmid("15765463", "Vasoactive intestinal peptide in autoimmune and inflammatory diseases", "Curr Opin Investig Drugs", "2005")],
  ),
  researchPartial(
    "matrixyl",
    "Matrixyl",
    "Peptid",
    "Matrixyl (Palmitoyl-Pentapeptid-4) ist ein kosmetisches Peptid aus der Dermatologie-Forschung.",
    "Matrixyl wurde in präklinischen und begrenzten Humanstudien als topisches Anti-Aging-Peptid untersucht.",
    "In präklinischen Modellen wurden Kollagen-stimulierende Effekte beschrieben. Humanwirksamkeit ist begrenzt dokumentiert.",
    "Topische Anwendung gilt als relativ gut verträglich.",
    "Primär topisch untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Begrenzte Humanstudien in kosmetischem Kontext.",
    "Präklinische Kollagen-Daten liegen vor.",
    "Kosmetische Forschung; keine Human-Zulassung als Arzneimittel.",
  ),
  bioregulatorPeptide("bronchogen", "Bronchogen", "Atemwegs- und Lungengewebe"),
  bioregulatorPeptide("cardiogen", "Cardiogen", "Herz- und Gefäßgewebe"),
  bioregulatorPeptide("cortagen", "Cortagen", "Nebennierenrinde und Stressachse"),
  bioregulatorPeptide("crystagen", "Crystagen", "Immunsystem und Lymphoidgewebe"),
  bioregulatorPeptide("cartalax", "Cartalax", "Knorpel- und Bindegewebe"),
  bioregulatorPeptide("livagen", "Livagen", "Lebergewebe"),
  bioregulatorPeptide("ovagen", "Ovagen", "Eierstock- und Reproduktionsgewebe"),
  bioregulatorPeptide("pancragen", "Pancragen", "Pankreasgewebe"),
  bioregulatorPeptide("pinealon", "Pinealon", "ZNS und Pinealdrüse"),
  bioregulatorPeptide("prostamax", "Prostamax", "Prostatagewebe"),
  bioregulatorPeptide("testagen", "Testagen", "Hoden- und Testesgewebe"),
  bioregulatorPeptide("thymalin", "Thymalin", "Thymus und Immunsystem"),
  bioregulatorPeptide("vesugen", "Vesugen", "Gefäß-Endothel"),
  bioregulatorPeptide("vilon", "Vilon", "Immunsystem und Thymus"),
  researchPartial(
    "p21",
    "P21",
    "Peptid",
    "P21 (Peptide 21) ist ein Cerebrolysin-Fragment-Analogon aus der Neuroprotektions-Forschung.",
    "P21 wurde in präklinischen Modellen der Neuroprotektion und kognitiven Funktion untersucht.",
    "In präklinischen Modellen wurden neuroprotektive Effekte beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische Neuroprotektions-Daten liegen vor.",
    "Überwiegend präklinische Forschung.",
  ),
  researchPartial(
    "pnc-27",
    "PNC-27",
    "Peptid",
    "PNC-27 ist ein p53-abgeleitetes Peptid aus der Onkologie-Forschung.",
    "PNC-27 wurde in präklinischen Modellen als antitumoraler Kandidat untersucht.",
    "In präklinischen Modellen wurden zytotoxische Effekte auf Tumorzellen beschrieben. Humanwirksamkeit ist nicht etabliert.",
    "Für den Human-Gebrauch liegen keine belastbaren Sicherheitsdaten vor.",
    "In präklinischen Studien untersucht. Im Shop als lyophilisiertes Peptid geführt – keine Anwendungsempfehlung.",
    "Keine Humanstudien identifiziert.",
    "Präklinische Onkologie-Daten liegen vor.",
    "Überwiegend präklinische Forschung.",
    [pmid("17299146", "PNC-27, a p53-derived peptide, causes tumor cell necrosis", "Int J Cancer", "2007")],
  ),
];
