import { fdaApprovedOral, pmid, researchPartial } from "@/lib/peptide/lexiconV2/contentEngine/pipeline/packBuilder";
import type { SubstanceCatalogEntry } from "@/lib/peptide/lexiconV2/contentEngine/pipeline/packBuilder";

const FDA_DAF = "https://www.accessdata.fda.gov/scripts/cder/daf/";

export const PIPELINE_SONSTIGE_ENTRIES: SubstanceCatalogEntry[] = [
  fdaApprovedOral(
    "epo",
    "Erythropoetin (EPO)",
    "Erythropoietin",
    "Anämie bei chronischer Niereninsuffizienz, Chemotherapie und anderen Indikationen (je nach Produkt)",
    "In Fachinformationen werden u. a. Hypertonie, Thromboembolie-Risiken und Antikörperbildung beschrieben.",
  ),
  researchPartial(
    "cerebrolysin",
    "Cerebrolysin",
    "Sonstige Substanz",
    "Cerebrolysin ist ein peptidhaltiges Nervenwachstumsfaktoren-Präparat aus Schweinehirn, in einigen Ländern für neurodegenerative Erkrankungen zugelassen.",
    "Cerebrolysin wird in Europa und Asien bei Demenz, Schlaganfall und TBI untersucht/verwendet. Zulassungsstatus variiert regional.",
    "In klinischen Studien bei Demenz und Schlaganfall wurden kognitive und funktionelle Endpunkte untersucht – heterogene Ergebnisse.",
    "In Fachinformationen werden u. a. allergische Reaktionen und Injection-site-Reaktionen beschrieben.",
    "Als intramuskuläre/intravenöse Injektion in zugelassenen Märkten. Im Shop als lyophilisiertes Präparat geführt – keine Anwendungsempfehlung.",
    "Mehrere klinische Studien in Europa; Zulassungsstatus variiert.",
    "Präklinische Neuroprotektions-Daten liegen vor.",
    "Regional zugelassen; nicht in allen Märkten etabliert.",
    [pmid("19701837", "Cerebrolysin in the treatment of mild cognitive impairment and dementia", "Drugs Today (Barc)", "2009")],
  ),
  researchPartial(
    "glutathione",
    "Glutathion",
    "Sonstige Substanz",
    "Glutathion ist ein tripeptidartiger Antioxidans-Cofaktor des Zellstoffwechsels.",
    "Glutathion wird in der Medizin als Antioxidans und Detoxifikations-Cofaktor untersucht. IV-Glutathion ist in einigen Kontexten etabliert.",
    "In Humanstudien wurden oxidativer Stress und Lebermarker untersucht – heterogene Ergebnisse.",
    "IV-Glutathion kann Bronchospasmen und allergische Reaktionen auslösen. Langzeitdaten variieren.",
    "In Humanstudien intravenös/inhalativ untersucht. Im Shop geführt – keine Dosierungsempfehlung.",
    "Humanstudien in spezifischen Indikationen liegen vor.",
    "Präklinische Antioxidans-Daten liegen vor.",
    "Investigational in vielen Indikationen; etabliert in spezifischen Kontexten.",
    [pmid("14984445", "Glutathione metabolism and its implications for health", "J Nutr", "2004")],
  ),
  researchPartial(
    "b12",
    "Vitamin B12",
    "Sonstige Substanz",
    "Vitamin B12 (Cobalamin) ist ein essentieller Cofaktor für DNA-Synthese und neurologische Funktion.",
    "Vitamin B12 ist zur Behandlung von B12-Mangel und perniziöser Anämie etabliert.",
    "In zugelassenen Indikationen ist Wirksamkeit etabliert.",
    "In therapeutischen Dosen meist gut verträglich; selten allergische Reaktionen.",
    "Als intramuskuläre Injektion etabliert. Im Shop geführt – keine Dosierungsempfehlung.",
    "Humanstudien und klinische Erfahrung liegen vor.",
    "Präklinische Daten liegen vor.",
    "Etabliertes Vitamin in medizinischen Indikationen.",
    [
      {
        id: "fda-b12",
        title: "Cyanocobalamin — FDA approved drug products",
        url: FDA_DAF,
        publisher: "FDA",
        publicationDate: null,
        accessDate: "2026-08-29",
        doi: null,
        pmid: null,
        clinicalTrialId: null,
        sourceType: "regulatory",
        sourceQuality: 5,
      },
    ],
  ),
  researchPartial(
    "hyaluronic-acid",
    "Hyaluronsäure",
    "Sonstige Substanz",
    "Hyaluronsäure ist ein glycosaminoglycanartiger Polysaccharid-Bestandteil des Bindegewebes.",
    "Hyaluronsäure ist in der Orthopädie (Gelenkinjektion), Dermatologie und Ophthalmologie etabliert.",
    "In zugelassenen Indikationen (z. B. viskosupplementation) ist Wirksamkeit beschrieben.",
    "Lokale Reaktionen an der Injektionsstelle sind möglich.",
    "Als intraartikuläre/topische Injektion etabliert. Im Shop geführt – keine Anwendungsempfehlung.",
    "Humanstudien für zugelassene Indikationen liegen vor.",
    "Präklinische Gewebe-Daten liegen vor.",
    "Etabliert in medizinischen und kosmetischen Indikationen.",
  ),
  researchPartial(
    "alprostadil",
    "Alprostadil",
    "Sonstige Substanz",
    "Alprostadil (Prostaglandin E1) ist ein vasoaktives Prostaglandin.",
    "Alprostadil ist für Erektile Dysfunktion (Caverject), PDA (Patent ductus arteriosus) und periphere arterielle Verschlusskrankheit zugelassen.",
    "In zugelassenen Indikationen ist Wirksamkeit etabliert.",
    "In Fachinformationen werden u. a. Penisschmerzen, Hypotension und Injection-site-Reaktionen beschrieben.",
    "Als intrakavernöse/intravenöse Injektion etabliert. Im Shop geführt – keine Anwendungsempfehlung.",
    "Humanstudien und Zulassungsdaten liegen vor.",
    "Präklinische Prostaglandin-Daten liegen vor.",
    "Zugelassenes Humanarzneimittel in mehreren Indikationen.",
    [
      {
        id: "fda-alprostadil",
        title: "Alprostadil — FDA prescribing information",
        url: FDA_DAF,
        publisher: "FDA",
        publicationDate: null,
        accessDate: "2026-08-29",
        doi: null,
        pmid: null,
        clinicalTrialId: null,
        sourceType: "regulatory",
        sourceQuality: 5,
      },
    ],
  ),
  researchPartial(
    "botulinum-toxin",
    "Botulinumtoxin",
    "Sonstige Substanz",
    "Botulinumtoxin ist ein Neurotoxin, das in der Medizin und Ästhetik weit verbreitet ist.",
    "Botulinumtoxin ist für Spastik, Migräne, Hyperhidrose und kosmetische Faltenbehandlung zugelassen (Botox, Dysport u. a.).",
    "In zugelassenen Indikationen ist Wirksamkeit etabliert.",
    "In Fachinformationen werden u. a. Muskelschwäche, Dysphagie und Botulismus-ähnliche Symptome bei Überdosierung beschrieben.",
    "Als intramuskuläre Injektion etabliert. Im Shop geführt – keine Anwendungsempfehlung.",
    "Humanstudien und Zulassungsdaten liegen vor.",
    "Präklinische Neurotoxin-Daten liegen vor.",
    "Zugelassenes Humanarzneimittel in mehreren Indikationen.",
    [
      {
        id: "fda-botox",
        title: "Botox (onabotulinumtoxinA) FDA prescribing information",
        url: FDA_DAF,
        publisher: "FDA",
        publicationDate: null,
        accessDate: "2026-08-29",
        doi: null,
        pmid: null,
        clinicalTrialId: null,
        sourceType: "regulatory",
        sourceQuality: 5,
      },
    ],
  ),
];
