/** Live cartwise-prod products (code, name) as of 2026-08-28. Read-only snapshot for mapping analysis. */
export const LIVE_SHOP_PRODUCTS: readonly { code: string; name: string }[] = [
  { code: "10AD", name: "AOD9604" },
  { code: "10AM", name: "5-amino-1mq" },
  { code: "1T100", name: "DHB (1-Test Cyp)" },
  { code: "1TT10", name: "DHB (1-Test Cyp)" },
  { code: "2AD", name: "AOD9604" },
  { code: "2S10", name: "SS-31" },
  { code: "2S50", name: "SS-31" },
  { code: "325", name: "T3" },
  { code: "340", name: "T3" },
  { code: "375", name: "LL37" },
  { code: "3R225", name: "TriTren 225mg" },
  { code: "440", name: "T4" },
  { code: "50AM", name: "5-amino-1mq" },
  { code: "5AD", name: "AOD9604" },
  { code: "5AM", name: "5-amino-1mq" },
  { code: "AA10", name: "AA Water" },
  { code: "AD5", name: "Adamax" },
  { code: "AE1", name: "ACE-031" },
  { code: "AI10", name: "AICAR" },
  { code: "AMQ50", name: "5-amino-1mq" },
  { code: "AP2", name: "Adipotide" },
  { code: "AP5", name: "Adipotide" },
  { code: "AR100", name: "Aicar" },
  { code: "AR50", name: "Aicar" },
  { code: "AU100", name: "AHK-CU" },
  { code: "B10F", name: "TB-500 (FRAG)" },
  { code: "B1201", name: "B12" },
  { code: "B1210", name: "B12" },
  { code: "B157", name: "BPC157" },
  { code: "B300", name: "BLEND 300mg" },
  { code: "B375", name: "BLEND 375mg" },
  { code: "B500", name: "BLEND 500mg" },
  { code: "B70", name: "COCK BOMBS" },
  { code: "BA03", name: "BAC Water" },
  { code: "BA10", name: "BAC Water" },
  { code: "BA100", name: "TEST BASE (NO Ester)" },
  { code: "BAM50", name: "BAM15" },
  { code: "BB10", name: "BPC157 5mg+TB500 5mg Blend" },
  { code: "BB20", name: "BPC157 10mg+TB500 10mg Blend" },
  { code: "BB500", name: "BPC 500mcg+TB500 500mcg Blend" },
  { code: "BBG70", name: "(GLOW) GHK-CU 50mg+TB500 10mg+BPC157 10mg Blend" },
  { code: "BC10", name: "BPC 157" },
  { code: "BC2", name: "BPC 157" },
  { code: "BC20", name: "BPC 157" },
  { code: "BC5", name: "BPC 157" },
  { code: "BC500", name: "BPC" },
  { code: "BM5", name: "Metribolone" },
  { code: "BR20", name: "Bronchogen" },
  { code: "BR50", name: "Tren BASE" },
  { code: "BS250", name: "BC (Boldenone Cyp)" },
  { code: "BT10", name: "TB-500 (Thymosin B4 Acetate)" },
  { code: "BT20", name: "TB-500 (Thymosin B4 Acetate)" },
  { code: "BT5", name: "TB-500 (Thymosin B4 Acetate)" },
  { code: "C250", name: "TEST CYPIONATE" },
  { code: "CA20", name: "Cardiogen" },
  { code: "CB40", name: "CLENBUTEROL" },
  { code: "CBL60", name: "Cerebrolysin" },
  { code: "CD10", name: "CJC-1295 With DAC" },
  { code: "CD2", name: "CJC-1295 With DAC" },
  { code: "CD5", name: "CJC-1295 With DAC" },
  { code: "CD50", name: "Clomiphene" },
  { code: "CG25", name: "Cabergoline" },
  { code: "CGL10", name: "Cagrilintide" },
  { code: "CGL20", name: "Cagrilintide" },
  { code: "CGL5", name: "Cagrilintide" },
  { code: "CND10", name: "CJC-1295 Without DAC" },
  { code: "CND2", name: "CJC-1295 Without DAC" },
  { code: "CND5", name: "CJC-1295 Without DAC" },
  { code: "COR20", name: "Cortagen" },
  { code: "CP10", name: "CJC-1295 without DAC 5mg + IPA 5mg Blend" },
  { code: "CP20", name: "CJC-1295 without DAC 10mg + IPA 10mg" },
  { code: "CRY20", name: "Crystagen" },
  { code: "CS10", name: "Cagrilintide 5mg+Semaglutide 5mg Blend" },
  { code: "CT10", name: "Turinabol" },
  { code: "CT25", name: "Turinabol" },
  { code: "CT50", name: "Turinabol" },
  { code: "CU100", name: "GHK-CU" },
  { code: "CU50", name: "GHK-CU" },
  { code: "D10", name: "DIANABOL" },
  { code: "D100", name: "Mast P (DP)" },
  { code: "D20", name: "DIANABOL" },
  { code: "D200", name: "Mast E (DE)" },
  { code: "D50", name: "DIANABOL" },
  { code: "DAP30", name: "dapoxetine" },
  { code: "DEX1", name: "ARIMIDEX" },
  { code: "DHA20", name: "Dihexa" },
  { code: "DM200", name: "MAST Blend 200mg" },
  { code: "DO50", name: "DIANABOL (Methandranstenolone)" },
  { code: "DR5", name: "Dermorphin" },
  { code: "DS10", name: "DSIP" },
  { code: "DS15", name: "DSIP" },
  { code: "DS2", name: "DSIP" },
  { code: "DS5", name: "DSIP" },
  { code: "DT20", name: "Tadalafil (Cialis)" },
  { code: "DUT1", name: "Dutasteride" },
  { code: "E3K", name: "EPO" },
  { code: "EC100", name: "Estradiol Cypionate" },
  { code: "EC25", name: "Androxal (Enclomiphene)" },
  { code: "ET10", name: "Epithalon" },
  { code: "ET40", name: "Epithalon" },
  { code: "ET50", name: "Epithalon" },
  { code: "EX25", name: "Aromasin (Exemestane)" },
  { code: "F410", name: "FOXO4" },
  { code: "FM2", name: "MGF" },
  { code: "FMP2", name: "PEG MGF" },
  { code: "FNA1", name: "Finasteride" },
  { code: "FR10", name: "HGH Fragment 176-191" },
  { code: "FR2", name: "HGH Fragment 176-191" },
  { code: "FR5", name: "HGH Fragment 176-191" },
  { code: "FS5", name: "Finasteride" },
  { code: "FX10", name: "Fluoxymesterone (Halotestin)" },
  { code: "G10K", name: "HCG" },
  { code: "G210", name: "GHRP-2 Acetate" },
  { code: "G25", name: "GHRP-2 Acetate" },
  { code: "G2K", name: "HCG" },
  { code: "G50", name: "GW-501516 (Cardarine)" },
  { code: "G5K", name: "HCG" },
  { code: "G610", name: "GHRP-6 Acetate" },
  { code: "G65", name: "GHRP-6 Acetate" },
  { code: "G75", name: "HMG" },
  { code: "GGH", name: "GGH" },
  { code: "GND2", name: "Gonadorelin" },
  { code: "GTT", name: "Glutathione" },
  { code: "H06", name: "HGH" },
  { code: "H10", name: "HGH" },
  { code: "H100", name: "Tren Hex" },
  { code: "H12", name: "HGH" },
  { code: "H15", name: "HGH" },
  { code: "H24", name: "HGH" },
  { code: "H36", name: "HGH" },
  { code: "H50", name: "HGH" },
  { code: "HA5", name: "Hyaluronic acid" },
  { code: "HD50", name: "DHT (Stanolone)" },
  { code: "HHB", name: "HHB" },
  { code: "HU10", name: "Humanin" },
  { code: "HX2", name: "Hexarelin" },
  { code: "HX5", name: "Hexarelin" },
  { code: "HYD200", name: "Hydroxychloroquine" },
  { code: "IG01", name: "IGF-1LR3" },
  { code: "IG1", name: "IGF-1LR3" },
  { code: "IP10", name: "Ipamorelin" },
  { code: "IP2", name: "Ipamorelin" },
  { code: "IP5", name: "Ipamorelin" },
  { code: "ISO10", name: "isotretinoin" },
  { code: "KL80", name: "(KLOW) GHK-CU 50mg+TB500 10mg+BPC157 10mg+TB500 10mg Blend" },
  { code: "KP10", name: "KPV" },
  { code: "KP5", name: "KPV" },
  { code: "KP500", name: "KPV" },
  { code: "KS10", name: "KissPeptin-10" },
  { code: "KS5", name: "KissPeptin-10" },
  { code: "LAX20", name: "Cartalax" },
  { code: "LC500", name: "LC500" },
  { code: "LC526", name: "LC526" },
  { code: "LC653", name: "LC653" },
  { code: "LGD", name: "LGD-4033 (Ligandrol)" },
  { code: "LI20", name: "Livagen" },
  { code: "LL10", name: "Liraglutide" },
  { code: "LL30", name: "Liraglutide" },
  { code: "LL5", name: "Liraglutide" },
  { code: "LV5", name: "Ivermectin" },
  { code: "LZ25", name: "Letrozole" },
  { code: "M100", name: "Primobolan E" },
  { code: "M1T10", name: "17a-Methyl-1-testosterone" },
  { code: "M200", name: "Primobolan E" },
  { code: "M25", name: "Methenolone Acetate (Primobolan)" },
  { code: "M28", name: "Ostarine / MK-2866" },
  { code: "M40", name: "Methenolone Acetate (Primobolan)" },
  { code: "M50", name: "Methenolone Acetate (Primobolan)" },
  { code: "M6", name: "MK-677 (Ibutamoren)" },
  { code: "MA10", name: "Matrixyl" },
  { code: "MAX20", name: "Prostamax" },
  { code: "MB20", name: "Methylene Blue" },
  { code: "MD5", name: "Minoxidil" },
  { code: "MDT10", name: "Mazdutide" },
  { code: "MDT5", name: "Mazdutide" },
  { code: "ML10", name: "MT-2 (Melanotan 2 Acetate)" },
  { code: "MN50", name: "MENT (Testosterone Acetate)" },
  { code: "MS10", name: "MOTS-C" },
  { code: "MS40", name: "MOTS-C" },
  { code: "MSB10", name: "Methylstenbolone" },
  { code: "MT1", name: "MT-1" },
  { code: "N200", name: "DECA (ND)" },
  { code: "N300", name: "DECA (ND)" },
  { code: "NET10", name: "N-Acetyl Epitalon Amidate" },
  { code: "NET5", name: "N-Acetyl Epitalon Amidate" },
  { code: "NJ100", name: "NAD+" },
  { code: "NJ1000", name: "NAD+" },
  { code: "NJ250", name: "NAD+" },
  { code: "NJ3100", name: "NAD+" },
  { code: "NJ500", name: "NAD+" },
  { code: "NM300", name: "NANDROMIX 300mg" },
  { code: "NP810", name: "SNAP-8" },
  { code: "NSK30", name: "NA Selank amide" },
  { code: "NXA30", name: "NA Semax amide" },
  { code: "ORF12", name: "Orforglipron" },
  { code: "ORF6", name: "Orforglipron" },
  { code: "OT10", name: "Oxytocin Acetate" },
  { code: "OT2", name: "Oxytocin Acetate" },
  { code: "OT5", name: "Oxytocin Acetate" },
  { code: "OV20", name: "Ovagen" },
  { code: "OXO50", name: "ANADROL (Oxymetholone)" },
  { code: "OXP50", name: "ANADROL" },
  { code: "P10", name: "Proviron" },
  { code: "P100", name: "TEST P" },
  { code: "P200", name: "TEST P" },
  { code: "P210", name: "P21" },
  { code: "P25", name: "Proviron" },
  { code: "P41", name: "PT-141" },
  { code: "PA20", name: "Pancragen" },
  { code: "PBN40", name: "Prednisone" },
  { code: "PE10", name: "PE 22-28" },
  { code: "PIN10", name: "Pinealon" },
  { code: "PIN20", name: "Pinealon" },
  { code: "PIN5", name: "Pinealon" },
  { code: "PN10", name: "PNC 27" },
  { code: "PN100", name: "NPP" },
  { code: "PN200", name: "NPP" },
  { code: "PN5", name: "PNC 27" },
  { code: "PND", name: "DNP" },
  { code: "PRO20", name: "Aprostadil" },
  { code: "R100", name: "Tren A" },
  { code: "R14", name: "RAD140" },
  { code: "R200", name: "Tren E" },
  { code: "RA10", name: "ARA-290" },
  { code: "RC10", name: "Retatrutide 5mg+Cagrilintide 5mg Blend" },
  { code: "RM200", name: "TRENMIX 200mg" },
  { code: "RT10", name: "Retatrutide" },
  { code: "RT100", name: "Retatrutide" },
  { code: "RT15", name: "Retatrutide" },
  { code: "RT20", name: "Retatrutide" },
  { code: "RT30", name: "Retatrutide" },
  { code: "RT40", name: "Retatrutide" },
  { code: "RT5", name: "Retatrutide" },
  { code: "RT50", name: "Retatrutide" },
  { code: "RT60", name: "Retatrutide" },
  { code: "RX225", name: "RIPEX" },
  { code: "RY100", name: "Tren E" },
  { code: "S040", name: "Andarine S4" },
  { code: "S250", name: "Sustanon 250mg" },
  { code: "S400", name: "Sustanon 400mg" },
  { code: "S450", name: "Supertest 450mg" },
  { code: "S9", name: "SR9009" },
  { code: "SB20", name: "SALBUTAMOL" },
  { code: "SB300", name: "slupp-332 250mcg+BAM15 50mcg" },
  { code: "SD10", name: "Superdrol" },
  { code: "SD100", name: "Sildenafil (Viagra)" },
  { code: "SDO50", name: "Superdrol (Methyldrostanolone)" },
  { code: "SHB", name: "SHB" },
  { code: "SK10", name: "Selank" },
  { code: "SK30", name: "Selank" },
  { code: "SK5", name: "Selank" },
  { code: "SL100", name: "SLU-PP-332" },
  { code: "SL50", name: "SLU-PP-332" },
  { code: "SLU1000", name: "SLU-PP-332" },
  { code: "SLU20", name: "SLU-PP-332" },
  { code: "SLU250", name: "SLU-PP-332" },
  { code: "SLU5", name: "SLU-PP-332" },
  { code: "SLU500", name: "SLU-PP-332" },
  { code: "SM10", name: "Semaglutide" },
  { code: "SM15", name: "Semaglutide" },
  { code: "SM2", name: "Semaglutide" },
  { code: "SM20", name: "Semaglutide" },
  { code: "SM30", name: "Semaglutide" },
  { code: "SM5", name: "Semaglutide" },
  { code: "SM500", name: "Semaglutide" },
  { code: "SMM3", name: "Semaglutide" },
  { code: "SMM7", name: "Semaglutide" },
  { code: "SMO10", name: "Sermorelin Acetate" },
  { code: "SMO15", name: "Sermorelin Acetate" },
  { code: "SMO5", name: "Sermorelin Acetate" },
  { code: "SO100", name: "STANOZOLOL (Oil base) winstrol" },
  { code: "SO50", name: "STANOZOLOL (Oil base) winstrol" },
  { code: "SP100", name: "TEST SUSPENSION 100mg" },
  { code: "SW100", name: "STANOZOLOL (Water) winstrol" },
  { code: "SW50", name: "STANOZOLol (Water) winstrol" },
  { code: "T20", name: "Tamoxifen (Nolvadex)" },
  { code: "T500", name: "Tesofensine" },
  { code: "T600", name: "Testo 600mg" },
  { code: "TA10", name: "Thymosin Alpha-1" },
  { code: "TA5", name: "Thymosin Alpha-1" },
  { code: "TE250", name: "TEST ENANTHATE" },
  { code: "TE300", name: "TEST ENANTHATE" },
  { code: "TER10", name: "Teriparatide" },
  { code: "TG20", name: "Testagen" },
  { code: "TI18", name: "Tesamorelin 12mg+Ipamorelin 6mg" },
  { code: "TM40", name: "Telmisartan" },
  { code: "TR10", name: "Tirzepatide" },
  { code: "TR100", name: "Tirzepatide" },
  { code: "TR120", name: "Tirzepatide" },
  { code: "TR15", name: "Tirzepatide" },
  { code: "TR20", name: "Tirzepatide" },
  { code: "TR30", name: "Tirzepatide" },
  { code: "TR40", name: "Tirzepatide" },
  { code: "TR5", name: "Tirzepatide" },
  { code: "TR50", name: "Tirzepatide" },
  { code: "TR500", name: "Tirzepatide" },
  { code: "TR60", name: "Tirzepatide" },
  { code: "TSM10", name: "Tesamorelin" },
  { code: "TSM20", name: "Tesamorelin" },
  { code: "TSM5", name: "Tesamorelin" },
  { code: "TY10", name: "Thymalin" },
  { code: "TY300", name: "TEST Undecanoate 300" },
  { code: "U200", name: "BU (EQUIPOISE)" },
  { code: "U300", name: "BU (EQUIPOISE)" },
  { code: "U600", name: "BU (EQUIPOISE)" },
  { code: "VE20", name: "Vesugen" },
  { code: "VI20", name: "Vilon" },
  { code: "VP10", name: "VIP" },
  { code: "W10", name: "Winstrol (Stanozolol)" },
  { code: "W20", name: "Winstrol (Stanozolol)" },
  { code: "W50", name: "Winstrol (Stanozolol)" },
  { code: "X10", name: "ANAVAR" },
  { code: "X25", name: "ANAVAR" },
  { code: "X50", name: "ANAVAR" },
  { code: "XA10", name: "Semax" },
  { code: "XA30", name: "Semax" },
  { code: "XA5", name: "Semax" },
  { code: "XS20", name: "Semax 10mg+Selank 10mg" },
  { code: "XT100", name: "Botulinum toxin" },
  { code: "Y1", name: "YK11" },
];
